# Use GitHub Actions version 2.1
name: 'test'
on:
  push:
    branches:
      - main
inputs:
  airgap-enabled:
    description: 'Enable airgap build'
    required: false
    default: 'false'

jobs:
  test-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set env variables
        uses: actions/checkout@v2
        env:
          CLIENT_BUILD_NAME: "${{ inputs.airgap-enabled == 'true' && 'client-build-airgap' || 'client-build' }}"
          CLIENT_BUILD_PATH: "${{ inputs.airgap-enabled == 'true' && 'app/client/build_airgap' || 'app/client/build' }}"
      - name: Log environment variables
        run: |
          echo "CLIENT_BUILD_NAME=${CLIENT_BUILD_NAME}"
          echo "CLIENT_BUILD_PATH=${CLIENT_BUILD_PATH}"

