# Use GitHub Actions version 2.1
name: 'test'
on:
  push:
    branches:
      - main


jobs:
  test-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        uses: actions/checkout@v2
      - name: Set Env vars
        run: |
         if [[ '${{ inputs.airgap-enabled }}' == true ]]; then
          echo 'client_build_name=client-build-airgap' >> "$GITHUB_ENV"
          echo 'client_build_path=app/client/build_airgap' >> "$GITHUB_ENV"
         else
          echo 'client_build_name=client-build-airgap' >> "$GITHUB_ENV"
          echo 'client_build_path=app/client/build_airgap' >> "$GITHUB_ENV"
          fi
      - name: Log environment variables
        run: |
          echo "client_build_name: ${{ env.client_build_name }}"
          echo "client_build_path: ${{ env.client_build_path }}"

